### ISSUE TITLE
Release in public docker repository.

### ISSUE THREAD

**Issue by andrejpetras** [infinispan/infinispan-quarkus-server#6]
Hi @wburns,

do you have any plans to release this project in the public docker registry?

I believe current state is not for production but for testing is a huge benefit to have small and fast infinispan server. Currently I am using it for testing with a testcontainers.

Docker registry of my build: https://quay.io/repository/lorislab/infinispan-quarkus-server?tab=tags

**Comment by ryanemerson** [comment]
@andrejpetras Hi! It is our intention to release an upstream image of the quarkus server in the near future, however I can't guarantee when that will be. I have just created https://github.com/infinispan/infinispan-images/issues/37 so you can follow it's progress and/or provide any feedback/ideas.

**Comment by andrejpetras** [comment]
@ryanemerson thank you for the info.

**Comment by wburns** [comment]
That is the goal for sure @andrejpetras!  At this point I am waiting until Quarkus has a release that officially supports GraalVM 19.3.1 or newer so we can baseline the server on Java 11 (current plans are Quarkus 1.2 for this).
